<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Welcome to the Bike Shop_emailInput</name>
   <tag></tag>
   <elementGuidId>02e90382-0b30-478b-a7c0-46538a81f397</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#emailInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='emailInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5d7bde8-8357-405f-9e5c-94a0c4537e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>8dcd4842-b014-4432-b38d-221dcc3a4680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>emailInput</value>
      <webElementGuid>24b580eb-cfb8-4ffe-b111-206dc59281ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter your email</value>
      <webElementGuid>e176b25c-ab3e-4e1e-b5da-938ba7fc460b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>validateEmail()</value>
      <webElementGuid>274eebf6-0722-4c00-9cc3-4befd0a0681a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;emailInput&quot;)</value>
      <webElementGuid>de9c5be5-d050-4ca0-87d6-5b47f29d6654</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='emailInput']</value>
      <webElementGuid>b2f9f696-79e4-475f-95a6-828d2c836ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>ed2307ef-ac36-423f-8cac-142e01be3962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @id = 'emailInput' and @placeholder = 'Enter your email']</value>
      <webElementGuid>e2a4a943-7740-49be-8827-7bdfe4606b1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
