<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Incorrect login details</name>
   <tag></tag>
   <elementGuidId>8175a039-ecfa-4347-b6af-44934eb8462b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#popupContent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='popupContent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>0c60974b-8106-443c-bb5a-942e0a1ba7e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>popupContent</value>
      <webElementGuid>54765432-6f0a-4ac3-bc92-88a73a407f39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Incorrect login details.</value>
      <webElementGuid>029f77f7-1667-4656-bf81-015ad6062add</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popupContent&quot;)</value>
      <webElementGuid>d47c4ab2-6f5a-4b8e-8dbe-bce3232fe392</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='popupContent']</value>
      <webElementGuid>9464646f-661e-4232-a7a8-bcd6be4282f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myPopup']/div/p</value>
      <webElementGuid>3022affb-a175-4e14-8d6e-eb405f60f843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::p[1]</value>
      <webElementGuid>c99c8b14-936a-48fa-b91b-ee7a3a523bc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::p[1]</value>
      <webElementGuid>ed244ff3-f76d-4e2a-bc73-b2ecab759b7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Incorrect login details.']/parent::*</value>
      <webElementGuid>e7563440-ba3d-416d-a8f2-ae78b3cb4ad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/p</value>
      <webElementGuid>8a43ad32-6b88-4b5a-888b-19cbcfe8ff49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'popupContent' and (text() = 'Incorrect login details.' or . = 'Incorrect login details.')]</value>
      <webElementGuid>3c9d6cc7-6d59-4fa8-a0dc-241b981e7cc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
